[project]
name = "ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "alembic>=1.14.0",
    "asyncpg>=0.30.0",
    "httpx>=0.28.0",
    "sqlalchemy>=2.0.0",
    "tqdm>=4.0.0",
    "domain"
]

[project.scripts]
cluelink-ingest = "ingest.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13"]
build-backend = "uv_build"

[tool.uv.sources]
domain = { workspace = true }
